// Auto-generated by scripts/generate-version.sh — do not edit manually.
public enum BuildVersion {
    public static let commit = "658d01f"
    public static let date = "2026-04-14 21:10 UTC"
    public static let branch = "build-local"
    public static let display = "658d01f (2026-04-14 21:10 UTC)"
}
